name: CI  
on:
  push:
    branches: [ main ]
jobs:
  node-build-publish:
    uses: nunnam/infrastructure/.github/workflows/ci.yml@main
    with: 
      nodejs-version: "16.x"
      unittest-npm-cmd: "test"
