name: CI

on:
  workflow_dispatch:

jobs:
  node-build-publish:
    uses: nunnam/infrastructure/.github/workflows/serverless-ci-cd.yaml
    with: 
      nodejs-version: 18.x
      unittest-npm-cmd: "test"
      
      
