name: CI

on:
  workflow_dispatch:

jobs:
  node-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  docker:
    uses: nunnam/infrastructure/.github/workflows/serverless-ci-cd.yaml@main
    with: 
      nodejs-version: "18.x"
      unittest-npm-cmd: "test"
